export const GET_EVENTLIST = "GET_EVENTLIST";
export const SELECT_EVENT = "SELECT_EVENT";
export const REMOVE_SELECTED_EVENT = "REMOVE_SELECTED_EVENT";
export const MAKE_EVENT_UNSELECTABLE = "MAKE_EVENT_UNSELECTABLE";
export const REMOVE_ERROR_STATE = "REMOVE_ERROR_STATE";